# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-20 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='catagory',
            new_name='category',
        ),
    ]
