# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-28 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180128_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
